import 'package:freezed_annotation/freezed_annotation.dart';

import '../../../../core/sync/sync_engine.dart';
import 'sync_status.dart';

part 'notebook_entry.freezed.dart';

/// One user-authored vocabulary note.
///
/// Provenance fields ([episodeId], [sentenceIndex]) are optional so users
/// can also add free-form words that are not tied to a specific transcript
/// line.
///
/// [meaning] may be null when the entry was created offline — the
/// "fill-later" strategy (architecture.md §오프라인 사전 조회) lets us save
/// the word now and enrich the translation when the device reconnects.
///
/// Conforms to [SyncableEntity] so the generic [SyncEngine] can process
/// notebook rows directly; the required `id` + `lastModified` getters are
/// generated by freezed from the factory above.
@freezed
class NotebookEntry with _$NotebookEntry implements SyncableEntity {
  const factory NotebookEntry({
    required String id,
    required String word,
    required String context,
    required DateTime createdAt,
    required DateTime lastModified,
    required SyncStatus syncStatus,
    String? episodeId,
    int? sentenceIndex,
    String? meaning,
    String? note,
  }) = _NotebookEntry;
}
